# Generated by Django 4.1.4 on 2022-12-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_link', models.CharField(max_length=100)),
                ('job_name', models.CharField(max_length=200)),
                ('job_addr', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('salary', models.CharField(max_length=30)),
            ],
        ),
    ]
