# Generated by Django 4.1.4 on 2022-12-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.CharField(default='學歷不拘', max_length=10),
        ),
        migrations.AddField(
            model_name='job',
            name='work_experience',
            field=models.CharField(default='經歷不拘', max_length=10),
        ),
    ]
