# Generated by Django 4.1.4 on 2022-12-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_education_job_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(max_length=50),
        ),
    ]
