# Generated by Django 4.1.4 on 2022-12-31 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_platform_job_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='web',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.platform'),
        ),
    ]
