# Generated by Django 4.1.4 on 2023-01-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_job_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
